### ISSUE TITLE
csctl publish uses dash instead of dot

### ISSUE THREAD

**Issue by jschoone** [SovereignCloudStack/csctl#155]
/kind bug

**What steps did you take and what happened:**
```
git clone https://github.com/SovereignCloudStack/cluster-stacks
git clone https://github.com/SovereignCloudStack/csctl
cd csctl
make build
./csctl create -m hash -o .release ../cluster-stacks/providers/openstack/scs
```

**What did you expect to happen:**
When using `csctl publish` the assets are uploaded in the format e.g. `openstack-scs-1-28-v0-sha.umng5ie` but the operator expects `openstack-scs-1-28-v0-sha-umng5ie`.
If there are no reasons for using the dot, csctl should just create and publish them with a dash.
The problem probably already occurs when creating the assets with `csctl create`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- csctl version: (use `csctl version`)
- OS (e.g. from `/etc/os-release`):

**Comment by DEiselt** [comment]
The string used as tag is created in [config.go](https://github.com/SovereignCloudStack/csctl/blob/853465873637e5dff5e845eef338dfed102b5c11/pkg/clusterstack/config.go#L143). The offending part is read from the `metadata.yaml` file directly `metada.Versions.ClusterStack` Which already contains the dot.

My question would be if the string should only be adapted for use as tag or if it should be saved with dash instead of dot in the first place.
